import * as PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as AWS from 'aws-sdk';
import { logger } from '../utils/logger';

export interface PlanData {
  name: string;
  user: {
    name: string;
    email: string;
  };
  startDate: Date;
  endDate?: Date;
  weeks: number;
  days: Array<{
    date: Date;
    weekday: string;
    isRestDay: boolean;
    sessions: Array<{
      title: string;
      description?: string;
      totalDuration: number;
      intensity: string;
      exercises: any[];
    }>;
  }>;
}

export class PdfService {
  private s3: AWS.S3;
  private bucket: string;

  constructor() {
    const endpoint = process.env.S3_ENDPOINT;
    const region = process.env.S3_REGION || 'us-east-1';
    const useMinio = process.env.USE_MINIO === 'true';

    this.bucket = process.env.S3_BUCKET_EXPORTS || 'planmaker-exports';

    this.s3 = new AWS.S3({
      endpoint: useMinio ? endpoint : undefined,
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
      region,
      s3ForcePathStyle: useMinio,
      signatureVersion: 'v4',
    });

    logger.info('📄 PDF service initialized');
  }

  async generatePlanPdf(planData: PlanData): Promise<string> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', async () => {
          try {
            const pdfBuffer = Buffer.concat(chunks);
            const key = `plans/${planData.user.email}/${Date.now()}-plan.pdf`;

            await this.s3
              .putObject({
                Bucket: this.bucket,
                Key: key,
                Body: pdfBuffer,
                ContentType: 'application/pdf',
                ACL: 'public-read',
              })
              .promise();

            const url = this.getFileUrl(key);
            logger.info(`✅ PDF generated and uploaded: ${key}`);
            resolve(url);
          } catch (error) {
            reject(error);
          }
        });

        // Generate PDF content
        this.buildPdfContent(doc, planData);
        doc.end();
      } catch (error) {
        logger.error('❌ Failed to generate PDF', error);
        reject(error);
      }
    });
  }

  private buildPdfContent(doc: PDFKit.PDFDocument, data: PlanData): void {
    // Header
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('Your Personalized Plan', { align: 'center' });

    doc.moveDown();

    // Plan info
    doc.fontSize(12).font('Helvetica');
    doc.text(`Plan: ${data.name}`);
    doc.text(`User: ${data.user.name}`);
    doc.text(`Start Date: ${data.startDate.toLocaleDateString()}`);
    doc.text(`Duration: ${data.weeks} weeks`);

    doc.moveDown(2);

    // Days and sessions
    let currentWeek = 0;
    data.days.forEach((day, index) => {
      const weekNumber = Math.floor(index / 7) + 1;

      if (weekNumber !== currentWeek) {
        currentWeek = weekNumber;
        doc
          .addPage()
          .fontSize(18)
          .font('Helvetica-Bold')
          .text(`Week ${weekNumber}`, { underline: true });
        doc.moveDown();
      }

      // Day header
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .text(`${day.weekday} - ${day.date.toLocaleDateString()}`);

      doc.moveDown(0.5);

      if (day.isRestDay) {
        doc.fontSize(12).font('Helvetica-Oblique').text('Rest Day', { indent: 20 });
      } else {
        day.sessions.forEach((session) => {
          doc.fontSize(12).font('Helvetica-Bold').text(session.title, { indent: 20 });

          doc
            .fontSize(10)
            .font('Helvetica')
            .text(`Duration: ${session.totalDuration} min | Intensity: ${session.intensity}`, {
              indent: 40,
            });

          if (session.description) {
            doc.fontSize(10).text(session.description, { indent: 40 });
          }

          if (session.exercises && session.exercises.length > 0) {
            session.exercises.forEach((ex: any) => {
              const exerciseText = `• ${ex.name || 'Exercise'}`;
              doc.fontSize(9).text(exerciseText, { indent: 60 });
            });
          }

          doc.moveDown(0.5);
        });
      }

      doc.moveDown();
    });

    // Footer
    doc
      .fontSize(10)
      .font('Helvetica-Oblique')
      .text('Generated by PlanMaker - Your AI-powered planning assistant', {
        align: 'center',
      });
  }

  private getFileUrl(key: string): string {
    const endpoint = process.env.S3_ENDPOINT;
    const useMinio = process.env.USE_MINIO === 'true';

    if (useMinio) {
      return `${endpoint}/${this.bucket}/${key}`;
    }

    return this.s3.getSignedUrl('getObject', {
      Bucket: this.bucket,
      Key: key,
      Expires: 3600 * 24 * 7, // 7 days
    });
  }
}
